services:
  stick-it-server:
    image: lrprojects/stick-it-server:0.0.16
    container_name: stick-it-server
    restart: unless-stopped
    volumes:
    - ./firebase-token.json:/app/firebase-token.json
    env_file:
    - ./.env
    networks:
    - db
    - influxdb-network
    - frontend
    labels:
    - traefik.enable=true
    - traefik.http.routers.stick-it.rule=Host(`stick-it.thinkpad.lr-projects.de`)
    - traefik.http.routers.stick-it.entrypoints=websecure
    - traefik.http.routers.stick-it.tls=true
    - traefik.http.routers.stick-it.tls.certresolver=cloudflare
    - traefik.http.services.stick-it.loadbalancer.server.port=8080
    - traefik.docker.network=frontend
    annotations:
    - de.lr-projects.description=Stick It backend
    - de.lr-projects.sso=false
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  stick-it-web:
    image: ghcr.io/lr101/stick-it:main
    container_name: stick-it-web
    restart: unless-stopped
    networks:
    - frontend
    labels:
    - traefik.enable=true
    - traefik.http.routers.stick-it-web.rule=Host(`stick-it-web.thinkpad.lr-projects.de`)
    - traefik.http.routers.stick-it-web.entrypoints=websecure
    - traefik.http.routers.stick-it-web.tls=true
    - traefik.http.routers.stick-it-web.tls.certresolver=cloudflare
    - traefik.http.services.stick-it-web.loadbalancer.server.port=80
    - traefik.docker.network=frontend
    annotations:
    - de.lr-projects.description=Stick It Web app
    - de.lr-projects.sso=false
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 100M

  
networks:
  influxdb-network:
    external: true
  db:
    external: true
  frontend:
    external: true
