version: 2

backends:
  drive:
    type: rclone
    path: drive:backup/medion
  local:
    type: local
    path: /backup
  nas:
    type: sftp
    path: nas:/backup_medion


global:
  forget:
    keep-last: 5
    keep-daily: 7
    keep-weekly: 4
    keep-monthly: 12
    keep-yearly: 7


monitors:
  stats:
    type: influx

locations:
  docker-tags:
    from:
    - ./.backup
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
    hooks:
      before: /hooks/docker-tags-hook.sh

  immich:
    from:
    - ./immich-app
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
    options:
      backup:
        exclude:
        - '*/postgres/*'
        - '*/library/thumbs/*'
        - '*/library/encoded-video/*'
  
  jellyfin:
    from:
    - ./jellyfin
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
  logging:
    from:
    - ./logging
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
    options:
      backup:
        exclude:
        - '*/influx_backup/*'
        - '*/influx/influx_data/*'
        - '*/prometheus/data/*'
  nextcloud:
    from:
    - ./nextcloud
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
    hooks:
      before:
      - docker exec nextcloud-nextcloud-1 /var/www/html/occ maintenance:mode  --on
      - python3 /hooks/mariadb-hook.py nextcloud-database-1 nextcloud --folder nextcloud
      after:
      - docker exec nextcloud-nextcloud-1 /var/www/html/occ maintenance:mode  --off

  pocketid:
    from:
    - ./pocket-id
    to:
    - local
    - drive
    - nas
    monitors:
    - stats

  stick-it-homepage:
    from:
    - ./stick-it-homepage
    to:
    - local
    - nas
    - drive
    monitors:
    - stats

  traefik:
    from:
    - ./traefik
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
    
  adguard:
    from:
    - /shared/adguard
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
