# Global Agent Configuration
[agent]
  interval = "10s" # Collection interval
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  logfile = ""
  debug = false
  quiet = false
  omit_hostname = false
  snmp_translator = "gosmi"
   
# Output Plugin: InfluxDB
[[outputs.influxdb_v2]]
  urls = ["${INFLUXDB_URL}"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.diskio]]
  skip_serial_number = true
[[inputs.disk]]

# Get kernel statistics from /proc/stat
[[inputs.kernel]]
  # no configuration

# Read metrics about memory usage
[[inputs.mem]]
  # no configuration

# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration

# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration

# Read metrics about system load & uptime
[[inputs.system]]

[[inputs.nstat]]

[[inputs.netstat]]


[[inputs.snmp]]
  agents = ["udp://127.0.0.1:161"]
  version = 2
  community = "public"
  interval = "60s"
  timeout = "5s"
  retries = 2
  agent_host_tag = "source"

  [[inputs.snmp.table]]
    name = "synology_disk"

    [[inputs.snmp.table.field]]
      name = "disk"
      oid = "1.3.6.1.4.1.6574.2.1.1.12"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "status"
      oid = "1.3.6.1.4.1.6574.2.1.1.5"

    [[inputs.snmp.table.field]]
      name = "temperature"
      oid = "1.3.6.1.4.1.6574.2.1.1.6"

    [[inputs.snmp.table.field]]
      name = "bad_sectors"
      oid = "1.3.6.1.4.1.6574.2.1.1.9"

    [[inputs.snmp.table.field]]
      name = "health"
      oid = "1.3.6.1.4.1.6574.2.1.1.13"

  [[inputs.snmp.table]]
    name = "synology_raid"

    [[inputs.snmp.table.field]]
      name = "raid"
      oid = "1.3.6.1.4.1.6574.3.1.1.2"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "status"
      oid = "1.3.6.1.4.1.6574.3.1.1.3"
