version: 2

backends:
  drive:
    type: rclone
    path: drive_lr101:backup/thinkpad
  nas:
    type: sftp
    path: nas:/backup_thinkpad
  local:
    type: local
    path: /backup


global:
  forget:
    keep-last: 5
    keep-daily: 7
    keep-weekly: 4
    keep-monthly: 12
    keep-yearly: 7


monitors:
  stats:
    type: influx


locations:
  docker-tags:
    from:
    - ./.backup
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
    hooks:
      before: /hooks/docker-tags-hook.sh
  
  glance:
    from:
    - ./glance
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
  
  ha:
    from:
    - ./ha
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
    hooks:
      before:
      - python3 /hooks/mariadb-hook.py mariadb homeassistant --folder ha
  
  monaserver:
    from:
    - ./monaserver
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
  
  postgis:
    from:
    - ./postgis
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
    hooks:
      before:
      - python3 /hooks/postgres-hook.py stick-it-db postgres stickitprod tempserver
        --backup-dir postgis/.backup
    options:
      backup:
        exclude:
          - '/postgres-data/*'
  
  tempserver:
    from:
    - ./tempserver
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
  
  traefik:
    from:
    - ./traefik
    to:
    - local
    - nas
    - drive
    monitors:
    - stats
